# Generated by Django 5.0.6 on 2024-06-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='inf0',
            field=models.CharField(max_length=1500),
        ),
    ]
