# Generated by Django 5.0.6 on 2024-06-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_serials_inf0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serials',
            old_name='inf0',
            new_name='info',
        ),
    ]
